services:
  # Backend service
  - type: web
    name: number-wars-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # Frontend service
  - type: web
    name: number-wars-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: REACT_APP_SERVER_URL
        value: https://number-wars-server.onrender.com
      - key: PORT
        value: 3000 